os: linux
sudo: required

services:
  - docker

script:
  - GIT_SHA="$(git rev-parse --short HEAD)"
  
  - docker build -f Dockerfile -t $AK_REG_USER/frontend:latest  -t $AK_REG_USER/frontend:$GIT_SHA ./frontend
  - docker build -f Dockerfile -t $REGISTRY_USER/backend:latest -t $REGISTRY_USER/backend:$GIT_SHA ./backend
  
  - echo "$AK_REG_PW" | docker login --username $AK_REG_USER --password-stdin
  - docker push $AK_REG_USER/frontend:latest 
  - docker push $AK_REG_USER/frontend:$GIT_SHA

  - echo "$REGISTRY_PASSWORD" | docker login --username $REGISTRY_USER --password-stdin
  - docker push $REGISTRY_USER/backend:latest 
  - docker push $REGISTRY_USER/backend:$GIT_SHA
