os: linux
sudo: required

services:
  - docker
    
env: 
  - DOCKER_COMPOSE_VERSION: 1.25.2

before_install:
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose

script:
  - docker version
  - docker-compose version
  - docker-compose build
  - docker-compose up -d --build
  - echo "$REGISTRY_PASSWORD" | docker login --username $REGISTRY_USER --password-stdin
  - docker-compose push
  
after_script:
  - docker-compose down
