os: linux
sudo: required

services:
  - docker

script:
  - GIT_SHA="$(git rev-parse --short HEAD)"
  
  - docker build -f ./frontend/Dockerfile -t $AK_REG_USER/frontend:latest  -t $AK_REG_USER/frontend:$GIT_SHA ./frontend
  - docker build -f ./backend/Dockerfile -t $AK_REG_USER/backend:latest -t $AK_REG_USER/backend:$GIT_SHA ./backend
  - docker build -f ./db/Dockerfile -t $AK_REG_USER/db:latest -t $AK_REG_USER/db:$GIT_SHA ./db
  
  - echo "$AK_REG_PW" | docker login --username $AK_REG_USER --password-stdin
  - docker push $AK_REG_USER/frontend:latest 
  - docker push $AK_REG_USER/frontend:$GIT_SHA

  - docker push $AK_REG_USER/backend:latest 
  - docker push $AK_REG_USER/backend:$GIT_SHA
  
  - docker push $AK_REG_USER/db:latest 
  - docker push $AK_REG_USER/db:$GIT_SHA
