version: '3'
services:
    backend:
        build: 
            context: ./backend
            dockerfile: Dockerfile
        image: kazefreedom/backend:latest
        volumes:
            - ./backend/process:/backend/process
            - ./backend/uploads:/backend/uploads
        ports:
            - "5000:5000"
    redis:
        image: "redis:alpine"
