version: '3'
services:
    frontend:
        container_name: clc-frontend
        build:
            context: ./frontend
        ports: 
            - "80:80"

    backend:
        container_name: clc-backend
        build: 
            context: ./backend
            dockerfile: Dockerfile
        image: kazefreedom/backend:latest
        volumes:
            - ./backend/process:/backend/process
            - ./backend/uploads:/backend/uploads
        ports:
            - "5000:5000"

    redis:
        container_name: clc-db
        image: "redis:alpine"
