version: '3'
services:
    frontend:
        container_name: clc-frontend
        image: alenkocaj/frontend:latest
        build:
            context: ./frontend
        ports: 
            - "80:80"

    redis:
        container_name: clc-db
        image: alenkocaj/db:latest
        build: 
            context: ./db
        ports:
            - "6379:6379"

    backend:
        container_name: clc-backend
        image: alenkocaj/backend:latest
        build: 
            context: ./backend
        volumes:
            - ./backend/process:/backend/process
            - ./backend/uploads:/backend/uploads
        ports:
            - "5000:5000"
        depends_on:
            - frontend
            - redis